# Generated by Django 2.2 on 2019-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=65, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
