# Generated by Django 2.2 on 2019-04-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL')),
                ('price', models.CharField(default=None, max_length=15, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('metro', models.CharField(blank=True, max_length=300, verbose_name='Метро')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Телефон')),
                ('created_at', models.DateField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
