# Generated by Django 2.1.7 on 2019-03-15 16:53

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20190315_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('PRIVATE_PERSON', 'Частное лицо'), ('LEGAL_PERSON', 'Юридическое лицо'), ('REALTOR', 'Риэлтор')], max_length=50, protected=True, verbose_name='Вид профиля')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profile.User', verbose_name='Пользователь'),
        ),
    ]
