# Generated by Django 2.1.7 on 2019-03-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20190315_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='view',
        ),
    ]
