# Generated by Django 2.1.7 on 2019-03-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100, verbose_name='Название')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=7, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Телефон')),
                ('created_at', models.DateField(verbose_name='Дата создания')),
            ],
        ),
    ]
