# Generated by Django 2.1.7 on 2019-03-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='products',
            name='number',
            field=models.CharField(default='6773736161', max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
