# Generated by Django 2.1.7 on 2019-03-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='metro',
            field=models.CharField(blank=True, max_length=300, verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
