# Generated by Django 2.1.5 on 2019-03-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190323_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(default=None, max_length=15, verbose_name='Цена'),
        ),
    ]
