# Generated by Django 2.1.7 on 2019-03-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190315_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='number',
            field=models.CharField(default='9144087464', max_length=10, verbose_name='Номер объявления'),
        ),
    ]
