# Generated by Django 2.1.7 on 2019-03-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190315_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='number',
            field=models.CharField(default='8014290539', max_length=10, verbose_name='Номер объявления'),
        ),
    ]
