# Generated by Django 2.1.7 on 2019-03-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190315_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='number',
            field=models.CharField(default='6520069341', max_length=10, verbose_name='Номер объявления'),
        ),
    ]
